services:
  frontend:
      build:
        context: .
        dockerfile: ./webapp/Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        - ./webapp:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
      stdin_open: true
      tty: true
      networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PERMIT_API_KEY=${PERMIT_API_KEY}
    volumes:
      - ./backend/app:/app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
