services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PERMIT_API_KEY=${PERMIT_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/app:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}    
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: