services:
  frontend:
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PERMIT_API_KEY=${PERMIT_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge